[versions]
junit = "6.0.2"
ktlint = "1.5.0"
# DO NOT DELETE - Used by the Micronaut Gradle plugin.
micronaut = "4.10.7"
# Also set in settings.gradle.kts
micronautPlugin = "4.6.2"
mockito = "5.21.0"

[libraries]
assertk = "com.willowtreeapps.assertk:assertk:0.28.1"
detekt-imports = "com.pkware.detekt:import-extension:1.2.0"
jspecify = "org.jspecify:jspecify:1.0.0"
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
mockito-kotlin = "org.mockito.kotlin:mockito-kotlin:6.2.3"
moshi = "com.squareup.moshi:moshi:1.15.2"

[plugins]
kotlin-allOpen = { id = "org.jetbrains.kotlin.plugin.allopen", version = "2.3.10" }
ksp = "com.google.devtools.ksp:2.2.21-2.0.4"
micronaut-aot = { id = "io.micronaut.aot", version.ref = "micronautPlugin" }
micronaut-library = { id = "io.micronaut.library", version.ref = "micronautPlugin" }

[bundles]
mockito = ["mockito-core", "mockito-junit", "mockito-kotlin"]
